replicaCount: 1

image:
  repository: registry.minter.network/node-walletconnect-bridge
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets:
  - name: registry.minter.network

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 5001

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: wallet-connect.minter.network
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: wallet-connect.minter.network
      hosts:
        - wallet-connect.minter.network

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

redis:
  architecture: standalone
  auth:
    enabled: false
  replica:
    replicaCount: 0
