version: '3.7'

networks:
  default:

volumes:
  redis:
  letsencrypt:

services:
  redis:
    image: 'redis:5-alpine'
    volumes:
      - redis:/data

  # This naming of the docker containers completely defeats the
  # purpose of Docker swarm and docker load balancing
  # so we are instead handling the load balancing with
  # our own nginx container
  bridge0:
    image: test-wallet
    environment:
      NODE_ENV: development
      REDIS_URL: redis://redis:6379/0
    ports:
      - target: 5001
        published: 5001
        mode: host
  bridge1:
    image: test-wallet
    environment:
      NODE_ENV: development
      REDIS_URL: redis://redis:6379/0
